apiVersion: "v1.0.0"
kind: "DataProduct"
id: "ce0fe2fa-54f5-4b6e-a315-31e6043bcda9"
name: "Test product"
status: "in development"
description: {}
team:
  name: "test-team"
customProperties:
- property: "type"
  value: "source-aligned"
- property: "visibility"
  value: "public"
domain: "test-domein"
outputPorts:
- name: "test-product"
  version: "0"
  contractId: "test-product"
  customProperties:
  - property: "displayName"
    value: "Test product"
